### ISSUE TITLE
Menu QA

### ISSUE THREAD

**Issue by kylamedina** [shifteight-dev/HarleyandCo#18]
- [x] Safari isn't center social correctly. Remove positioning css from `#menu-overlay .socials` and put it on `#menu-overlay .SE_socials-wrapper` instead
```css
#menu-overlay .SE_socials-wrapper {
display: flex;
justify-content: center;
position: absolute;
bottom: 50px;
width: 100%;
}
#menu-overlay .socials {
margin: 40px auto auto auto;
}

```

- [x] We are going to make animations in a later phase but do you mind speeding up the open and close transition a bit for the time being?
