### ISSUE TITLE
Services QA

### ISSUE THREAD

**Issue by kylamedina** [shifteight-dev/HarleyandCo#20]
- [x] Please but the services in a 1440px container
- [x] Can you make links 1px underline? 
```css
#services #services-list .service .tc.content p a::before {
    border-top: 1px solid #3d3d3d;
}
```
- [x] A little less padding:
```css
#services #services-list .service .tc.content h4 {
    padding: 10px 0 25px 0;
}
```

-  [x] The sup title should be the same style as the filters on the homepage.
